import './globals.css'
import { Inter } from 'next/font/google'

import MainHeader from '@/components/atoms/typography/MainHeader'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-full flex flex-col gap-2 pr-4 pl-4 pb-5 ">
          <MainHeader />
          {children}
        </div>
      </body>
    </html>
  )
}
